name: Tamper-Proof Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  secure-build:
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE: version.txt
      ARCHIVE_FILE: source.zip
      SIGNATURE_FILE: source.sig

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 🏷️ Generate Unique Build Metadata
        run: |
          BUILD_ID="pounce-$(date +'%Y%m%d')-${{ github.run_number }}"
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: ✍️ Create Watermark File
        run: |
          echo "Pounce Official Build" > $OUTPUT_FILE
          echo "Build ID: $BUILD_ID" >> $OUTPUT_FILE
          echo "Commit: $COMMIT_HASH" >> $OUTPUT_FILE
          echo "Timestamp: $TIMESTAMP" >> $OUTPUT_FILE

      - name: ✒️ Inject Watermark into index.html
        run: |
          if [ -f index.html ]; then
            echo "<!-- Build ID: $BUILD_ID | Commit: $COMMIT_HASH -->" >> index.html
          fi

      - name: ❌ Fail if watermark is missing
        run: |
          if ! grep -rq "$BUILD_ID" .; then
            echo "❌ ERROR: Watermark ($BUILD_ID) not found in build output."
            exit 1
          fi

      - name: 📦 Package entire build into a zip archive
        run: |
          zip -r $ARCHIVE_FILE $OUTPUT_FILE index.html

      - name: 🔐 Import GPG Private Key
        run: |
          echo "$GPG_PRIV_KEY" | gpg --batch --import
        env:
          GPG_PRIV_KEY: ${{ secrets.GPG_PRIV_KEY }}

      - name: 🛠️ Configure GPG for CI
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          
      - name: 🖋️ Sign the Build
        run: |
          echo "$GPG_PRIV_PASS" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --armor --output "$SIGNATURE_FILE" --detach-sign "$ARCHIVE_FILE"
        env:
          GPG_PRIV_PASS: ${{ secrets.GPG_PRIV_PASS }}

      - name: ✅ Verify GPG Signature
        run: |
          gpg --verify "$SIGNATURE_FILE" "$ARCHIVE_FILE"

      - name: 📦 Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pounce-build
          path: |
            ${{ env.ARCHIVE_FILE }}
            ${{ env.SIGNATURE_FILE }}
          if-no-files-found: error
